language: c
sudo: required
services:
  - docker
before_install:  
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine
script:
  - make
  - docker run -t -v $PWD:/mnt xenserver/xenserver-build-env:lindig ./build xenopsd
